apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: blog-tls
  namespace: blog
  labels:
    app.kubernetes.io/name: blog
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`blog.thamimagi.dev`)
      kind: Rule
      services:
        - name: blog
          port: 80
  tls:
    secretName: blog-tls
